#+Author: Matt Scaperoth
#+EMAIL: mscapero@gwu.edu
#+STARTUP: showall

*** Tasks
<2014-05-31 Sat>-<2014-06-01 Sun>
**** DONE set up linux enviornment: 
Linux ubuntu 3.5.0-23-generic #35~precise1-Ubuntu SMP Fri Jan 25 17:13:26 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
**** DONE Create new repo with org file
**** DONE install qemu and add to repo: 
http://wiki.qemu.org/Hosts/Linux using the git, git clone git://git.qemu-project.org/qemu.git
**** DONE Install autoconf to run pistachio configure.in file
**** DONE install pistachio and add to repo: 
http://www.l4ka.org/154.php
set up the make menuconfig with x86 basic architecture, 64 bit sub architecture (processor architecture)
with a pentium4 processor type -- DESPITE SUGGESTION IN THE GUIDE FOUND AT THE LINK ABOVE, "...if you are planning to run the kernel using the Qemu emulator, then choose Pentium 1".     
Debugging mode enabled. Performance monitoring enabled.    
No options chosen for debugger.
***** TODO configure user level pistachio
unable to run configuration. used autoconf to build ../user/configure.in, but make is throwing errors.      

receiving error: "no rule to make target 'config.h', needed by 'amd64.o'. Stop.
