#+Author: Matt Scaperoth
#+EMAIL: mscapero@gwu.edu
#+STARTUP: showall

*** Tasks
<2014-05-31 Sat>-<2014-06-01 Sun>
**** DONE set up linux enviornment: 
Linux v 12.04: uname -- Linux ubuntu 3.11.0-22-generic #38~precise1-Ubuntu SMP i686 i686 i386 GNU/Linux 
**** DONE Create new repo with org file
**** DONE install qemu and aqemu
**** DONE Install autoconf to run pistachio configure.in file
**** TODO install pistachio and add to repo: 
http://www.l4ka.org/154.php
set up the make menuconfig with x86 basic architecture, 32 bit sub architecture (processor architecture)
with a pentium1  processor type 
Debugging mode enabled. Performance monitoring enabled.    
No options chosen for debugger.
***** DONE configure user level pistachio
unable to run configuration. used autoconf to build ../user/configure.in, but make is throwing errors.      

receiving error: "no rule to make target 'config.h', needed by 'amd64.o'. Stop.
FIX NOTE: used suggestion found @ https://lists.gnu.org/archive/html/nmh-workers/2008-08/msg00032.html. running autoheader then autoconf in the l4ka-pistachio/user/ folder resulted in a clean build.

***** TODO run pistachio on qemu
