#+Author: Matt Scaperoth
#+EMAIL: mscapero@gwu.edu
#+STARTUP: showall

*** Tasks
<2014-05-31 Sat>-<2014-06-01 Sun>
**** DONE set up linux enviornment: 
Linux v 12.04: uname -- Linux ubuntu 3.11.0-22-generic #38~precise1-Ubuntu SMP i686 i686 i386 GNU/Linux 
**** DONE Create new repo with org file
**** DONE install qemu and aqemu
**** DONE Install autoconf to run pistachio configure.in file
**** DONE install pistachio and add to repo: 
http://www.l4ka.org/154.php
set up the make menuconfig with x86 basic architecture, 32 bit sub architecture (processor architecture)
with a pentium1  processor type 
Debugging mode enabled. Performance monitoring enabled.    
No options chosen for debugger.
***** DONE configure user level pistachio
unable to run configuration. used autoconf to build ../user/configure.in, but make is throwing errors.      

receiving error: "no rule to make target 'config.h', needed by 'amd64.o'. Stop.

***** DONE
FIX NOTE: used suggestion found @ https://lists.gnu.org/archive/html/nmh-workers/2008-08/msg00032.html. running autoheader then autoconf in the l4ka-pistachio/user/ folder resulted in a clean build.

***** DONE 
unloaded grub2 and loaded grub legacy using instructions found at http://pclinuxos2007.blogspot.com/2010/09/linux-how-to-replace-grub2-with-grub.html      
Note: Better and more complete instructions used from http://ubuntuforums.org/showthread.php?t=1298932     
        
sudo mv /boot/grub /boot/grub_backup      

sudo mkdir /boot/grub      

sudo apt-get --purge remove startupmanager     

sudo apt-get --purge remove grub-pc grub-common    

sudo apt-get install grub     

sudo update-grub      

sudo fdisk -l <-- use this to find out which drive to install to     

sudo grub-install /dev/sda      

sudo grub      

find /boot/grub/stage1     

root (hd0,0)         

setup (hd0)         

**** DONE run pistachio on qemu
Followed instrctuions found at http://www.l4ka.org/120.php under the *Booting and Running* section.     

Exception to guide: Ran using /usr/sbin/grub and /usr/local/libexec/l4/ instead of /sbin/grub and l4ka-pistachio/x86-x32-user-install/libexec/l4/ respectively
     
final command once image was built: qemu -serial stdio -fda fdimage.img -boot c

